apiVersion: v1
appVersion: 0.18.1
description: A Helm chart for prometheus node-exporter
home: https://github.com/prometheus/node_exporter/
keywords:
- node-exporter
- prometheus
- exporter
maintainers:
- email: gopakumar.r@oracle.com
  name: Gopa
name: prometheus-node-exporter
sources:
- https://github.com/prometheus/node_exporter/
version: 1.8.2
